#!/usr/bin/python3
def raise_exception():
    result = 7 + "7"
    return result
